name: Makefile CI

on:
  push:
    branches: [ "upstream-5.15.x" ]
  pull_request:
    branches: [ "upstream-5.15.x" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compile
      run: make
    
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
          format: 'YYYY-MM-DD-HH-mm-ss'
        
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: "images_${{ steps.time.outputs.time }}"
        path: output/images/
